### ISSUE TITLE
track gas expenditure

### ISSUE THREAD

**Issue by sanchaymittal** [connext/vector#475] opened 2021-03-18 14:43 UTC
track gas expenditure vs fees collected in the router
now that we have fees up and running, we should figure out how much we're actually losing on router ops and what it would take to offset that cost
esp cause we've been yeeting several eth every couple of days into the router

https://discord.com/channels/454734546869551114/481078703309455361/822112332284952596

**Comment by LayneHaber** [comment] 2021-03-18 19:49
This is duplicate of #474

**Closed by LayneHaber** 2021-03-18 19:49 UTC
Labels: duplicate
