### ISSUE TITLE
[engine] Do not auto-submit your own withdrawals as Alice

### ISSUE THREAD

**Issue by rhlsthrm** [connext/vector#354] opened 2021-02-04 11:59 UTC
Currently, Alice submits withdrawals immediately when they are signed. This makes sense for Bob's withdrawals since Bob needs it immediately. However, Alice does not need to submit her own withdrawals immediately. Alice should hold onto her withdrawal commitments and only submit them when it makes sense (i.e. gas is low). Ideally, we can batch the commitments but even without batching it makes sense to hold onto them until later.

- [ ] Disable withdrawal submission by default for Alice's own withdrawals.
- [ ] Add config item to enable the above.
- [ ] Add endpoint to submit withdrawal(s) later.
- [ ] Endpoint should check if the withdrawal has already been submitted by checking the nonce against submitted txs.

**Comment by LayneHaber** [comment] 2021-02-05 20:13
Alice has never been autosubmitting her own withdrawals, see code [here](https://github.com/connext/vector/blob/e8329c50aed2322140df9005750b901d99ab9825/modules/engine/src/listeners.ts#L701-L707)

**Comment by LayneHaber** [comment] 2021-02-13 01:18
Duplicate of #358

**Closed by LayneHaber** 2021-02-13 01:18 UTC
Labels: help wanted, needs spec, p1
